### ISSUE TITLE
Permit user account authentication

### ISSUE THREAD

**Issue by crbn60** [lmtani/iap-auth#1]
Excellent work on this, makes life much easier, thank you.

I am writing a developer-only command line Python tool that will need to access an IAP-protected API, but using end-user credentials. It would be helpful to allow this in a simple way, maybe by doing the same type of browser auth that many other tools use, like `gcloud auth` for example.

Would this be difficult?

**Comment by lmtani** [comment]
Hi @crbn60 ! Thank you for your feedback. 

I think it will not be difficult to implement. Soon I'll give you an update.

**Comment by crbn60** [comment]
Thanks for looking into it @lmtani . 

Ideally, a user could simply execute:
```
$ gcloud auth application-default login --project versature-automation
```
Prior to running a script that is using this library to make requests thought IAP. Once that is performed, it appears you can get credentials using the `google.auth` library:
```
>>> import google.auth
>>> credentials, project = google.auth.default()
>>> print(credentials)
<google.oauth2.credentials.Credentials object at 0x10c38af70>
```

**Comment by lmtani** [comment]
Hello @crbn60 , I managed to make the script open the browser and ask for user credentials, similar to `gcloud auth application-default login` behavior.

If the login is successful then the script will store user credentials at the provided path and next time it will not be required. 

https://github.com/lmtani/iap-auth/tree/allow-user-authentication#authenticating-a-user-account

You can try it using: `pip install git+https://github.com/lmtani/iap-auth.git@allow-user-authentication`

Please let me know if this setup would be helpful.

**Comment by crbn60** [comment]
It works incredibly well @lmtani ! This is going to be a very helpful tool. I'll be using it for real work today, even. Thanks so much for taking the time to implement.

**Comment by lmtani** [comment]
That is great! Soon I'm going to publish this new release in pip.

**Comment by lmtani** [comment]
New release is out: https://pypi.org/project/iap-auth/. Code add in #2 

Closing this issue.
